#!/bin/bash

(( WHIPTAIL_OK=0 ))
(( WHIPTAIL_CANCEL=1 ))
(( WHIPTAIL_ESC=255 ))

inputbox() { #title, message, width, height, tmp_file, ok_string
	whiptail --title "$1" \
	  --clear \
	  --inputbox \
	"$2" $3 $4 2> $5

	return_value=$?

	case $return_value in
		$WHIPTAIL_OK)
			echo "$6 $(cat $5)"
			;;
		$WHIPTAIL_CANCEL)
			echo "Cancel pressed."
			;;
		$WHIPTAIL_ESC)
			if [ -s $5 ];then
				cat $5
			else
				echo "ESC pressed."
			fi
			;;
	esac
}

sch() { #tmp_file, dates
	whiptail --title "SCHEDULE" \
	  --clear \
	  --checklist \
	"Choose when you are scheduled:" 15 25 7 2> $1 2> $2 \
	"Monday" "" OFF \
	"Tuesday" "" OFF \
	"Wednesday" "" OFF \
	"Thursday" "" OFF \
	"Friday" "" OFF \
	"Saturday" "" OFF \
	"Sunday" "" OFF  

	return_value=$?

	case $return_value in
		$WHIPTAIL_OK)
			echo "Schedule: $(cat $1)"
			;;
		$WHIPTAIL_CANCEL)
			echo "Cancel pressed."
			;;
		$WHIPTAIL_ESC)
			if [ -s $1 ];then
				cat $1
			else
				echo "ESC pressed."
			fi
			;;
	esac
}

schStart() { #tmp_file
	whiptail --title "SCHEDULE" \
	  --clear \
	  --inputbox \
	"When will your schedule start? \nStart date (MM-DD-YYYY):" 15 30 2> $1

	return_value=$?

	case $return_value in
		$WHIPTAIL_OK)
			echo "Schedule start: $(cat $1)"
			;;
		$WHIPTAIL_CANCEL)
			echo "Cancel pressed."
			;;
		$WHIPTAIL_ESC)
			if [ -s $1 ];then
				cat $1
			else
				echo "ESC pressed."
			fi
			;;
	esac
}

schEnd() { #tmp_file
	whiptail --title "SCHEDULE" \
	  --clear \
	  --inputbox \
	"When will your schedule end? \nEnd date (MM-DD-YYYY):" 15 30 2> $1

	return_value=$?

	case $return_value in
		$WHIPTAIL_OK)
			echo "Schedule end: `cat $1`"
			;;
		$WHIPTAIL_CANCEL)
			echo "Cancel pressed."
			;;
		$WHIPTAIL_ESC)
			if [ -s $1 ];then
				cat $1
			else echo "ESC pressed."
			fi
			;;
	esac
}

timeStart() { #tmp_file, day_string, title
	whiptail --title "$3" \
		--clear \
		--inputbox \
	"Time start for $2" 20 25 2> $1

	return_value=$?

	case $return_value in
		$WHIPTAIL_OK)
			echo "$2 $(cat $1)"
			;;
		$WHIPTAIL_CANCEL)
			echo "Cancel pressed."
			;;
		$WHIPTAIL_ESC)
			if [ -s $1 ];then
				cat $1
			else
				echo "ESC pressed."
			fi
			;;
	esac
}

timeEnd() { #tmp_file, day_string, title
	whiptail --title "$3" \
		--clear \
		--inputbox \
	"Time end for $2" 20 25 2> $1

	return_value=$?

	case $return_value in
		$WHIPTAIL_OK)
			echo "$2 $(cat $1)"
			;;
		$WHIPTAIL_CANCEL)
			echo "Cancel pressed."
			;;
		$WHIPTAIL_ESC)
			if [ -s $1 ];then
				cat $1
			else
				echo "ESC pressed."
			fi
			;;
	esac
}

timeAgain() { #tmp_file, day_string, title
	whiptail --title "$3" \
		--clear \
		--yesno \
	"Add another time schedule for $2?" 15 30 2> $1

	return_value=$?

	case $return_value in
		$WHIPTAIL_OK)
			return $WHIPTAIL_OK
			;;
		$WHIPTAIL_CANCEL)
			return $WHIPTAIL_CANCEL
			;;
		$WHIPTAIL_ESC)
			if [ -s $1 ];then
				cat $1
			else
				return $WHIPTAIL_ESC
			fi
			;;
	esac
}
