#!/bin/bash

# Possible exit statuses
# WHIPTAIL_OK=0 
# WHIPTAIL_CANCEL=1 
# WHIPTAIL_ESC=255 

#3>&1 1>&2 2>&3 swaps stderr and stdout so we can store output in a variable

inputbox() { #title, message, width, height, tmp_file, ok_string
	whiptail --title "$1" \
	  --clear \
	  --inputbox \
	"$2" $3 $4 3>&1 1>&2 2>&3

	exit_status=$?
	return $exit_status
}

sch() { #tmp_file, dates
	whiptail --title "SCHEDULE" \
	  --clear \
	  --checklist \
	"Choose when you are scheduled:" 15 25 7 3>&1 1>&2 2>&3 \
	"Monday" "" OFF \
	"Tuesday" "" OFF \
	"Wednesday" "" OFF \
	"Thursday" "" OFF \
	"Friday" "" OFF \
	"Saturday" "" OFF \
	"Sunday" "" OFF  

	exit_status=$?
	return $exit_status
}

timeAgain() { #tmp_file, day_string, title
	whiptail --title "$3" \
		--clear \
		--yesno \
	"Add another time schedule for $2?" 15 30 3>&1 1>&2 2>&3

	exit_status=$?
	return $exit_status
}
